//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int sno { get; set; }
        public string sname { get; set; }
        public Nullable<decimal> fee { get; set; }
        public string course { get; set; }
    }
}
